//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBits.WinClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadDir0 {
            get {
                return ((string)(this["DownloadDir0"]));
            }
            set {
                this["DownloadDir0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UploadDir0 {
            get {
                return ((string)(this["UploadDir0"]));
            }
            set {
                this["UploadDir0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserNames {
            get {
                return ((string)(this["UserNames"]));
            }
            set {
                this["UserNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeWarning {
            get {
                return ((bool)(this["MinimizeWarning"]));
            }
            set {
                this["MinimizeWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ProgressDoneColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressDoneColor"]));
            }
            set {
                this["ProgressDoneColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color ProgressLeftColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressLeftColor"]));
            }
            set {
                this["ProgressLeftColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color ProgressCompletedColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressCompletedColor"]));
            }
            set {
                this["ProgressCompletedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GradientActiveCaption")]
        public global::System.Drawing.Color SelectedActiveColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedActiveColor"]));
            }
            set {
                this["SelectedActiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GradientInactiveCaption")]
        public global::System.Drawing.Color SelectedInactiveColor {
            get {
                return ((global::System.Drawing.Color)(this["SelectedInactiveColor"]));
            }
            set {
                this["SelectedInactiveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAllJobs {
            get {
                return ((bool)(this["ShowAllJobs"]));
            }
            set {
                this["ShowAllJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalPaths {
            get {
                return ((string)(this["LocalPaths"]));
            }
            set {
                this["LocalPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemotePaths {
            get {
                return ((string)(this["RemotePaths"]));
            }
            set {
                this["RemotePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableIEExtension {
            get {
                return ((bool)(this["EnableIEExtension"]));
            }
            set {
                this["EnableIEExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SharpBits.WinClient.JobWrapperCache JobCache {
            get {
                return ((global::SharpBits.WinClient.JobWrapperCache)(this["JobCache"]));
            }
            set {
                this["JobCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SharpBits.WinClient.CredentialsCache CredentialsCache {
            get {
                return ((global::SharpBits.WinClient.CredentialsCache)(this["CredentialsCache"]));
            }
            set {
                this["CredentialsCache"] = value;
            }
        }
    }
}
